### PR TITLE
Add item categories to items page

### PR DESCRIPTION
**Pull request by bighuggies**
Item categories now work on the items page.

The only thing missing is icons for the "all" category and the "misc" category.

itemcategories2

### CODE REVIEW

**Comment by bighuggies** [comment]
Something was missing, added a hover color to the tabs:

itemcategories3

**Comment by Skippeh** [comment]
Feels like the category images should be a little bit bigger. Try 50x50?

The active color is a bit hard to see as well. Could try make it stronger.

And to be extra nitpicky (:P), active category hover should be the same color as the active category but lighter imo.

**Comment by bighuggies** [comment]
How about this?

itemcategories_tweaks

**Comment by Skippeh** [comment]
Yeah that looks good. I'll merge it.

**Pull request merged**
